# Default values for homepage.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

nameOverride: ""
fullnameOverride: ""

imagePullSecrets:
  - name: "registry-jnhssg-de-registrycreds"
  - name: "ecr-registrycreds"

image:
  repository: registry.jnhssg.de/strapi
  pullPolicy: IfNotPresent
  tag: ""

probes:
  startupProbe:
    path: /health
    failureThreshold: 30
    periodSeconds: 2
  livenessProbe:
    path: /health
    periodSeconds: 5
  readinessProbe:
    path: /health
    periodSeconds: 5

service:
  name: http
  port: 3000

ingress:
  enabled: true

client:

  replicaCount: 1

  image:
    repository: registry.jnhssg.de/likedeeler-client
    pullPolicy: IfNotPresent
    tag: ""

  service:
    name: http
    port: 80
    healthEndpoint: /healthz

  ingress:
    enabled: true

  resources:
    limits:
      memory: 64Mi
    requests:
      cpu: 100m
      memory: 32Mi

cms:

  replicaCount: 1

  resources:
    limits:
      memory: 256Mi
    requests:
      cpu: 100m
      memory: 128Mi

  image:
    repository: registry.jnhssg.de/likedeeler-cms

  service:
    host: 0.0.0.0
    port: 1337
    name: http
    healthEndpoint: /health

  config:
    databaseClient: postgres
    databaseHost: ""
    databasePort: ""
    databaseUsername: ""
    databaseSsl: false
    awsRegion: eu-central-1

  secrets:
    appKeys: ""
    apiTokenSalt: ""
    adminJwtSecret: ""
    transferTokenSalt: ""
    databasePassword: ""
    jwtSecret: ""
    awsAccessKeyId: ""
    awsSecretAccessKey: ""
