apiVersion: v1
kind: Service
metadata:
  name: {{ include "likedeeler.fullname" . }}-client
spec:
  ports:
    - port: 80
      targetPort: {{ .Values.client.service.name }}
      name: http
  selector:
    {{- include "likedeeler.selectorLabels" . | nindent 4 }}-client
