apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "likedeeler.fullname" . }}-cms
spec:
  replicas: {{ .Values.replicaCount }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 80%
      maxUnavailable: 0
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "likedeeler.shortName" . }}-cms
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "likedeeler.shortName" . }}-cms
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.cms.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          livenessProbe:
            httpGet:
              path: {{ .Values.cms.service.healthEndpoint }}
              port: {{ .Values.cms.service.port }}
          readinessProbe:
            httpGet:
              path: {{ .Values.cms.service.healthEndpoint }}
              port: {{ .Values.cms.service.port }}
          startupProbe:
            httpGet:
              path: {{ .Values.cms.service.healthEndpoint }}
              port: {{ .Values.cms.service.port }}
            initialDelaySeconds: 10
            failureThreshold: 30
          ports:
            - name: {{ .Values.cms.service.name }}
              containerPort: {{ .Values.cms.service.port }}
          env:
            - name: ADMIN_JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: {{ include "likedeeler.shortName" . }}-secret
                  key: adminJwtSecret
            - name: API_TOKEN_SALT
              valueFrom:
                secretKeyRef:
                  name: {{ include "likedeeler.shortName" . }}-secret
                  key: apiTokenSalt
            - name: APP_KEYS
              valueFrom:
                secretKeyRef:
                  name: {{ include "likedeeler.shortName" . }}-secret
                  key: appKeys
            - name: TRANSFER_TOKEN_SALT
              valueFrom:
                secretKeyRef:
                  name: {{ include "likedeeler.shortName" . }}-secret
                  key: transferTokenSalt
            - name: DATABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "likedeeler.shortName" . }}-secret
                  key: databasePassword
            - name: AWS_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: {{ include "likedeeler.shortName" . }}-secret
                  key: awsAccessKeyId
            - name: AWS_ACCESS_SECRET
              valueFrom:
                secretKeyRef:
                  name: {{ include "likedeeler.shortName" . }}-secret
                  key: awsSecretAccessKey
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: {{ include "likedeeler.shortName" . }}-secret
                  key: jwtSecret
            - name: DATABASE_CLIENT
              value: "{{ .Values.cms.config.databaseClient }}"
            - name: DATABASE_HOST
              value: "{{ .Values.cms.config.databaseHost }}"
            - name: DATABASE_NAME
              value: "{{ .Values.cms.config.databaseName }}"
            - name: DATABASE_PORT
              value: "{{ .Values.cms.config.databasePort }}"
            - name: DATABASE_USERNAME
              value: "{{ .Values.cms.config.databaseUsername }}"
            - name: DATABASE_SSL
              value: "{{ .Values.cms.config.databaseSsl }}"
            - name: AWS_REGION
              value: "{{ .Values.cms.config.awsRegion }}"
            - name: AWS_BUCKET
              value: "{{ .Values.cms.config.awsBucket }}"
            - name: CLOUDFRONT_BASE_URL
              value: "{{ .Values.cms.config.cloudfrontBaseUrl }}"
          resources:
            {{- toYaml .Values.cms.resources | nindent 12 }}
