apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "likedeeler.fullname" . }}-cms
spec:
  replicas: {{ .Values.replicaCount }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 80%
      maxUnavailable: 0
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "likedeeler.shortName" . }}-cms
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "likedeeler.shortName" . }}-cms
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.cms.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: {{ .Values.cms.service.name }}
              containerPort: {{ .Values.cms.service.port }}
          env:
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: {{ include "likedeeler.shortName" . }}-secret
                  key: databaseUrl
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: {{ include "likedeeler.shortName" . }}-secret
                  key: jwtSecret
          resources:
            {{- toYaml .Values.cms.resources | nindent 12 }}
