apiVersion: v1
kind: Secret
metadata:
  name: {{ include "likedeeler.shortName" . }}-secret
type: Opaque
data:
  databaseUrl: {{ .Values.cms.secrets.databaseUrl | b64enc }}
  jwtSecret: {{ .Values.cms.secrets.jwtSecret | b64enc }}
