apiVersion: v1
kind: Secret
metadata:
  name: {{ include "likedeeler.shortName" . }}-secret
type: Opaque
data:
  appKeys: {{ .Values.cms.secrets.appKeys | b64enc }}
  apiTokenSalt: {{ .Values.cms.secrets.apiTokenSalt | b64enc }}
  adminJwtSecret: {{ .Values.cms.secrets.adminJwtSecret | b64enc }}
  transferTokenSalt: {{ .Values.cms.secrets.transferTokenSalt | b64enc }}
  databasePassword: {{ .Values.cms.secrets.databasePassword | b64enc }}
  jwtSecret: {{ .Values.cms.secrets.jwtSecret | b64enc }}
  awsAccessKeyId: {{ .Values.cms.secrets.awsAccessKeyId | b64enc }}
  awsSecretAccessKey: {{ .Values.cms.secrets.awsSecretAccessKey | b64enc }}
